import '@aws-amplify/ui-react/styles.css';
import { Suspense } from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import ConfigureAmplifyClientSide from '@/components/ConfigureAmplify';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ConfigureAmplifyClientSide />
				{children}
			</body>
		</html>
	);
}
