import '@aws-amplify/ui-react/styles.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { LayoutProvider } from '../layout/context/layoutcontext';
import { PrimeReactProvider } from 'primereact/api';
import '../styles/layout/layout.scss';
import 'primeflex/primeflex.css';
import 'primeicons/primeicons.css';
import 'primereact/resources/primereact.css';
import '../styles/demo/demo.scss';

import ConfigureAmplifyClientSide from '@/components/ConfigureAmplify';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" suppressHydrationWarning>
			<head>
				<link id="theme-link" href={`/theme/theme-dark/teal/theme.css`} rel="stylesheet"></link>
			</head>
			<body>
				<ConfigureAmplifyClientSide />
				<PrimeReactProvider>
					<LayoutProvider>{children}</LayoutProvider>
				</PrimeReactProvider>
			</body>
		</html>
	);
}
